import jsPDF from 'jspdf';
import { ComplianceReport, LegalNotice } from '../types';

export function generateLegalNoticeText(report: ComplianceReport, officerName: string = 'Field Inspector'): { text: string; noticeObj: LegalNotice } {
  const failedRules = report.results.filter(r => r.status === 'fail');
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const noticeNo = `PM-${Math.floor(100000 + Math.random() * 900000)}`;

  const mfdResult = report.results.find(r => r.ruleId === 'MANUFACTURER_ADDRESS');
  const manufacturerName = report.manufacturerName && report.manufacturerName !== 'Packer / Manufacturer' 
    ? report.manufacturerName 
    : "Manufacturer/Packer (unidentified — see attached evidence)";
  
  const manufacturerAddress = mfdResult?.matchedText || "Address Unidentified / Missing on PDP";

  const violationsList = failedRules.map((r, i) => `${i + 1}. ${r.legalRef} — ${r.title}`).join('\n');

  const text = `SHOW-CAUSE NOTICE
Issued under Section 36(1) of the Legal Metrology Act, 2009
read with Rule 6 of the Legal Metrology (Packaged Commodities) Rules, 2011

Notice No.: ${noticeNo}        Date: ${today}

To,
${manufacturerName}
${manufacturerAddress}

Subject: Show-cause notice for non-compliance with mandatory package declarations

Sir/Madam,

During inspection of the product "${report.productName || 'the above product'}" (Inspection ID: ${report.id}, dated ${today}), the following non-compliance(s) with the Legal Metrology (Packaged Commodities) Rules, 2011 were observed:

${violationsList}

You are hereby directed to show cause, in writing, within 15 days of receipt of this notice, as to why action should not be initiated against you under the applicable provisions of the Legal Metrology Act, 2009, for the above non-compliance(s).

Evidence: Annotated label image and OCR-extracted text are attached as evidence to this digital record.

This notice is generated by PackMetrics — an AI-assisted compliance system — and requires countersignature by an authorized Legal Metrology Officer before it is legally valid.

_____________________________
${officerName} (Draft — pending countersignature)`;

  const noticeObj: LegalNotice = {
    id: `NOT-${Date.now()}`,
    noticeNumber: noticeNo,
    scanId: report.id,
    date: today,
    manufacturerName,
    manufacturerAddress,
    productName: report.productName,
    violations: failedRules.map(r => ({ legalRef: r.legalRef, title: r.title, matchedText: r.matchedText })),
    status: 'Open',
    issuedBy: officerName,
  };

  return { text, noticeObj };
}

export function downloadNoticePDF(noticeText: string, noticeNumber: string) {
  const doc = new jsPDF();
  
  // Header styling
  doc.setFillColor(11, 31, 58); // Navy
  doc.rect(0, 0, 210, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('GOVERNMENT OF INDIA — LEGAL METROLOGY DIVISION', 15, 16);

  doc.setTextColor(11, 31, 58);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(noticeText, 180);
  doc.text(lines, 15, 38);

  // Footer disclaimer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Prototype output generated by PackMetrics for demonstration purposes — not a substitute for legal review.',
    15,
    pageHeight - 10
  );

  doc.save(`${noticeNumber}-ShowCauseNotice.pdf`);
}
